//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocalPIData.cems {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="cems.cemsSoap")]
    public interface cemsSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 HelloWorldResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        LocalPIData.cems.HelloWorldResponse HelloWorld(LocalPIData.cems.HelloWorldRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 pn 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddPiRecord", ReplyAction="*")]
        LocalPIData.cems.AddPiRecordResponse AddPiRecord(LocalPIData.cems.AddPiRecordRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 pn 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddRuleLogRd", ReplyAction="*")]
        LocalPIData.cems.AddRuleLogRdResponse AddRuleLogRd(LocalPIData.cems.AddRuleLogRdRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 pn 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdatePiRecord", ReplyAction="*")]
        LocalPIData.cems.UpdatePiRecordResponse UpdatePiRecord(LocalPIData.cems.UpdatePiRecordRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 pn 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateRuleLogRd", ReplyAction="*")]
        LocalPIData.cems.UpdateRuleLogRdResponse UpdateRuleLogRd(LocalPIData.cems.UpdateRuleLogRdRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 pn 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddPiRecord_c", ReplyAction="*")]
        LocalPIData.cems.AddPiRecord_cResponse AddPiRecord_c(LocalPIData.cems.AddPiRecord_cRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 pn 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdatePiRecord_c", ReplyAction="*")]
        LocalPIData.cems.UpdatePiRecord_cResponse UpdatePiRecord_c(LocalPIData.cems.UpdatePiRecord_cRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 pn 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddRuleLogRd_c", ReplyAction="*")]
        LocalPIData.cems.AddRuleLogRd_cResponse AddRuleLogRd_c(LocalPIData.cems.AddRuleLogRd_cRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 pn 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateRuleLog_c", ReplyAction="*")]
        LocalPIData.cems.UpdateRuleLog_cResponse UpdateRuleLog_c(LocalPIData.cems.UpdateRuleLog_cRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 enterprise 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddMonitorData_c", ReplyAction="*")]
        LocalPIData.cems.AddMonitorData_cResponse AddMonitorData_c(LocalPIData.cems.AddMonitorData_cRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 enterprise 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateMonitorData_c", ReplyAction="*")]
        LocalPIData.cems.UpdateMonitorData_cResponse UpdateMonitorData_c(LocalPIData.cems.UpdateMonitorData_cRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddExceptionGroup_c", ReplyAction="*")]
        int AddExceptionGroup_c(long lid, long envirid, int typeid, int pi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateExceptionGroup_c", ReplyAction="*")]
        int UpdateExceptionGroup_c(long lid, long envirid, int typeid, int pi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddExceptionRuleLog_c", ReplyAction="*")]
        int AddExceptionRuleLog_c(long lid, long envirid, long ruleid, int typeid, int pi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateExceptionRuleLog_c", ReplyAction="*")]
        int UpdateExceptionRuleLog_c(long lid, long envirid, long ruleid, int typeid, int pi);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public LocalPIData.cems.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(LocalPIData.cems.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public LocalPIData.cems.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(LocalPIData.cems.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddPiRecordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddPiRecord", Namespace="http://tempuri.org/", Order=0)]
        public LocalPIData.cems.AddPiRecordRequestBody Body;
        
        public AddPiRecordRequest() {
        }
        
        public AddPiRecordRequest(LocalPIData.cems.AddPiRecordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddPiRecordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime ts;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pn;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public float pv;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int mi;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int pi;
        
        public AddPiRecordRequestBody() {
        }
        
        public AddPiRecordRequestBody(System.DateTime ts, string pn, float pv, int mi, int pi) {
            this.ts = ts;
            this.pn = pn;
            this.pv = pv;
            this.mi = mi;
            this.pi = pi;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddPiRecordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddPiRecordResponse", Namespace="http://tempuri.org/", Order=0)]
        public LocalPIData.cems.AddPiRecordResponseBody Body;
        
        public AddPiRecordResponse() {
        }
        
        public AddPiRecordResponse(LocalPIData.cems.AddPiRecordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddPiRecordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int AddPiRecordResult;
        
        public AddPiRecordResponseBody() {
        }
        
        public AddPiRecordResponseBody(int AddPiRecordResult) {
            this.AddPiRecordResult = AddPiRecordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddRuleLogRdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddRuleLogRd", Namespace="http://tempuri.org/", Order=0)]
        public LocalPIData.cems.AddRuleLogRdRequestBody Body;
        
        public AddRuleLogRdRequest() {
        }
        
        public AddRuleLogRdRequest(LocalPIData.cems.AddRuleLogRdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddRuleLogRdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime ts;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pn;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string rn;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string rt;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string rd;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int mi;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int pi;
        
        public AddRuleLogRdRequestBody() {
        }
        
        public AddRuleLogRdRequestBody(System.DateTime ts, string pn, string rn, string rt, string rd, int mi, int pi) {
            this.ts = ts;
            this.pn = pn;
            this.rn = rn;
            this.rt = rt;
            this.rd = rd;
            this.mi = mi;
            this.pi = pi;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddRuleLogRdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddRuleLogRdResponse", Namespace="http://tempuri.org/", Order=0)]
        public LocalPIData.cems.AddRuleLogRdResponseBody Body;
        
        public AddRuleLogRdResponse() {
        }
        
        public AddRuleLogRdResponse(LocalPIData.cems.AddRuleLogRdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddRuleLogRdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int AddRuleLogRdResult;
        
        public AddRuleLogRdResponseBody() {
        }
        
        public AddRuleLogRdResponseBody(int AddRuleLogRdResult) {
            this.AddRuleLogRdResult = AddRuleLogRdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdatePiRecordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdatePiRecord", Namespace="http://tempuri.org/", Order=0)]
        public LocalPIData.cems.UpdatePiRecordRequestBody Body;
        
        public UpdatePiRecordRequest() {
        }
        
        public UpdatePiRecordRequest(LocalPIData.cems.UpdatePiRecordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdatePiRecordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime ts;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pn;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public float pv;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int mi;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int pi;
        
        public UpdatePiRecordRequestBody() {
        }
        
        public UpdatePiRecordRequestBody(System.DateTime ts, string pn, float pv, int mi, int pi) {
            this.ts = ts;
            this.pn = pn;
            this.pv = pv;
            this.mi = mi;
            this.pi = pi;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdatePiRecordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdatePiRecordResponse", Namespace="http://tempuri.org/", Order=0)]
        public LocalPIData.cems.UpdatePiRecordResponseBody Body;
        
        public UpdatePiRecordResponse() {
        }
        
        public UpdatePiRecordResponse(LocalPIData.cems.UpdatePiRecordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdatePiRecordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int UpdatePiRecordResult;
        
        public UpdatePiRecordResponseBody() {
        }
        
        public UpdatePiRecordResponseBody(int UpdatePiRecordResult) {
            this.UpdatePiRecordResult = UpdatePiRecordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateRuleLogRdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateRuleLogRd", Namespace="http://tempuri.org/", Order=0)]
        public LocalPIData.cems.UpdateRuleLogRdRequestBody Body;
        
        public UpdateRuleLogRdRequest() {
        }
        
        public UpdateRuleLogRdRequest(LocalPIData.cems.UpdateRuleLogRdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateRuleLogRdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime ts;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pn;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string rn;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string rt;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string rd;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int mi;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int pi;
        
        public UpdateRuleLogRdRequestBody() {
        }
        
        public UpdateRuleLogRdRequestBody(System.DateTime ts, string pn, string rn, string rt, string rd, int mi, int pi) {
            this.ts = ts;
            this.pn = pn;
            this.rn = rn;
            this.rt = rt;
            this.rd = rd;
            this.mi = mi;
            this.pi = pi;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateRuleLogRdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateRuleLogRdResponse", Namespace="http://tempuri.org/", Order=0)]
        public LocalPIData.cems.UpdateRuleLogRdResponseBody Body;
        
        public UpdateRuleLogRdResponse() {
        }
        
        public UpdateRuleLogRdResponse(LocalPIData.cems.UpdateRuleLogRdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateRuleLogRdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int UpdateRuleLogRdResult;
        
        public UpdateRuleLogRdResponseBody() {
        }
        
        public UpdateRuleLogRdResponseBody(int UpdateRuleLogRdResult) {
            this.UpdateRuleLogRdResult = UpdateRuleLogRdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddPiRecord_cRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddPiRecord_c", Namespace="http://tempuri.org/", Order=0)]
        public LocalPIData.cems.AddPiRecord_cRequestBody Body;
        
        public AddPiRecord_cRequest() {
        }
        
        public AddPiRecord_cRequest(LocalPIData.cems.AddPiRecord_cRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddPiRecord_cRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long lid;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime ts;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string pn;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public float pv;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int mi;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int pi;
        
        public AddPiRecord_cRequestBody() {
        }
        
        public AddPiRecord_cRequestBody(long lid, System.DateTime ts, string pn, float pv, int mi, int pi) {
            this.lid = lid;
            this.ts = ts;
            this.pn = pn;
            this.pv = pv;
            this.mi = mi;
            this.pi = pi;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddPiRecord_cResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddPiRecord_cResponse", Namespace="http://tempuri.org/", Order=0)]
        public LocalPIData.cems.AddPiRecord_cResponseBody Body;
        
        public AddPiRecord_cResponse() {
        }
        
        public AddPiRecord_cResponse(LocalPIData.cems.AddPiRecord_cResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddPiRecord_cResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int AddPiRecord_cResult;
        
        public AddPiRecord_cResponseBody() {
        }
        
        public AddPiRecord_cResponseBody(int AddPiRecord_cResult) {
            this.AddPiRecord_cResult = AddPiRecord_cResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdatePiRecord_cRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdatePiRecord_c", Namespace="http://tempuri.org/", Order=0)]
        public LocalPIData.cems.UpdatePiRecord_cRequestBody Body;
        
        public UpdatePiRecord_cRequest() {
        }
        
        public UpdatePiRecord_cRequest(LocalPIData.cems.UpdatePiRecord_cRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdatePiRecord_cRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long lid;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime ts;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string pn;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public float pv;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int mi;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int pi;
        
        public UpdatePiRecord_cRequestBody() {
        }
        
        public UpdatePiRecord_cRequestBody(long lid, System.DateTime ts, string pn, float pv, int mi, int pi) {
            this.lid = lid;
            this.ts = ts;
            this.pn = pn;
            this.pv = pv;
            this.mi = mi;
            this.pi = pi;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdatePiRecord_cResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdatePiRecord_cResponse", Namespace="http://tempuri.org/", Order=0)]
        public LocalPIData.cems.UpdatePiRecord_cResponseBody Body;
        
        public UpdatePiRecord_cResponse() {
        }
        
        public UpdatePiRecord_cResponse(LocalPIData.cems.UpdatePiRecord_cResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdatePiRecord_cResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int UpdatePiRecord_cResult;
        
        public UpdatePiRecord_cResponseBody() {
        }
        
        public UpdatePiRecord_cResponseBody(int UpdatePiRecord_cResult) {
            this.UpdatePiRecord_cResult = UpdatePiRecord_cResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddRuleLogRd_cRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddRuleLogRd_c", Namespace="http://tempuri.org/", Order=0)]
        public LocalPIData.cems.AddRuleLogRd_cRequestBody Body;
        
        public AddRuleLogRd_cRequest() {
        }
        
        public AddRuleLogRd_cRequest(LocalPIData.cems.AddRuleLogRd_cRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddRuleLogRd_cRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long lid;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime ts;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string pn;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string rt;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string rd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string cemstype;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int pi;
        
        public AddRuleLogRd_cRequestBody() {
        }
        
        public AddRuleLogRd_cRequestBody(long lid, System.DateTime ts, string pn, string rt, string rd, string cemstype, int pi) {
            this.lid = lid;
            this.ts = ts;
            this.pn = pn;
            this.rt = rt;
            this.rd = rd;
            this.cemstype = cemstype;
            this.pi = pi;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddRuleLogRd_cResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddRuleLogRd_cResponse", Namespace="http://tempuri.org/", Order=0)]
        public LocalPIData.cems.AddRuleLogRd_cResponseBody Body;
        
        public AddRuleLogRd_cResponse() {
        }
        
        public AddRuleLogRd_cResponse(LocalPIData.cems.AddRuleLogRd_cResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddRuleLogRd_cResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int AddRuleLogRd_cResult;
        
        public AddRuleLogRd_cResponseBody() {
        }
        
        public AddRuleLogRd_cResponseBody(int AddRuleLogRd_cResult) {
            this.AddRuleLogRd_cResult = AddRuleLogRd_cResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateRuleLog_cRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateRuleLog_c", Namespace="http://tempuri.org/", Order=0)]
        public LocalPIData.cems.UpdateRuleLog_cRequestBody Body;
        
        public UpdateRuleLog_cRequest() {
        }
        
        public UpdateRuleLog_cRequest(LocalPIData.cems.UpdateRuleLog_cRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateRuleLog_cRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long lid;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime ts;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string pn;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string rt;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string rd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string cemstype;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int pi;
        
        public UpdateRuleLog_cRequestBody() {
        }
        
        public UpdateRuleLog_cRequestBody(long lid, System.DateTime ts, string pn, string rt, string rd, string cemstype, int pi) {
            this.lid = lid;
            this.ts = ts;
            this.pn = pn;
            this.rt = rt;
            this.rd = rd;
            this.cemstype = cemstype;
            this.pi = pi;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateRuleLog_cResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateRuleLog_cResponse", Namespace="http://tempuri.org/", Order=0)]
        public LocalPIData.cems.UpdateRuleLog_cResponseBody Body;
        
        public UpdateRuleLog_cResponse() {
        }
        
        public UpdateRuleLog_cResponse(LocalPIData.cems.UpdateRuleLog_cResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateRuleLog_cResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int UpdateRuleLog_cResult;
        
        public UpdateRuleLog_cResponseBody() {
        }
        
        public UpdateRuleLog_cResponseBody(int UpdateRuleLog_cResult) {
            this.UpdateRuleLog_cResult = UpdateRuleLog_cResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddMonitorData_cRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddMonitorData_c", Namespace="http://tempuri.org/", Order=0)]
        public LocalPIData.cems.AddMonitorData_cRequestBody Body;
        
        public AddMonitorData_cRequest() {
        }
        
        public AddMonitorData_cRequest(LocalPIData.cems.AddMonitorData_cRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddMonitorData_cRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long lid;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime ts;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string enterprise;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string pn;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int indicatorid;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public double indicatorvalue;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int pi;
        
        public AddMonitorData_cRequestBody() {
        }
        
        public AddMonitorData_cRequestBody(long lid, System.DateTime ts, string enterprise, string pn, int indicatorid, double indicatorvalue, int pi) {
            this.lid = lid;
            this.ts = ts;
            this.enterprise = enterprise;
            this.pn = pn;
            this.indicatorid = indicatorid;
            this.indicatorvalue = indicatorvalue;
            this.pi = pi;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddMonitorData_cResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddMonitorData_cResponse", Namespace="http://tempuri.org/", Order=0)]
        public LocalPIData.cems.AddMonitorData_cResponseBody Body;
        
        public AddMonitorData_cResponse() {
        }
        
        public AddMonitorData_cResponse(LocalPIData.cems.AddMonitorData_cResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddMonitorData_cResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int AddMonitorData_cResult;
        
        public AddMonitorData_cResponseBody() {
        }
        
        public AddMonitorData_cResponseBody(int AddMonitorData_cResult) {
            this.AddMonitorData_cResult = AddMonitorData_cResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateMonitorData_cRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateMonitorData_c", Namespace="http://tempuri.org/", Order=0)]
        public LocalPIData.cems.UpdateMonitorData_cRequestBody Body;
        
        public UpdateMonitorData_cRequest() {
        }
        
        public UpdateMonitorData_cRequest(LocalPIData.cems.UpdateMonitorData_cRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateMonitorData_cRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long lid;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime ts;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string enterprise;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string pn;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int indicatorid;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public double indicatorvalue;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int pi;
        
        public UpdateMonitorData_cRequestBody() {
        }
        
        public UpdateMonitorData_cRequestBody(long lid, System.DateTime ts, string enterprise, string pn, int indicatorid, double indicatorvalue, int pi) {
            this.lid = lid;
            this.ts = ts;
            this.enterprise = enterprise;
            this.pn = pn;
            this.indicatorid = indicatorid;
            this.indicatorvalue = indicatorvalue;
            this.pi = pi;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateMonitorData_cResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateMonitorData_cResponse", Namespace="http://tempuri.org/", Order=0)]
        public LocalPIData.cems.UpdateMonitorData_cResponseBody Body;
        
        public UpdateMonitorData_cResponse() {
        }
        
        public UpdateMonitorData_cResponse(LocalPIData.cems.UpdateMonitorData_cResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateMonitorData_cResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int UpdateMonitorData_cResult;
        
        public UpdateMonitorData_cResponseBody() {
        }
        
        public UpdateMonitorData_cResponseBody(int UpdateMonitorData_cResult) {
            this.UpdateMonitorData_cResult = UpdateMonitorData_cResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface cemsSoapChannel : LocalPIData.cems.cemsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class cemsSoapClient : System.ServiceModel.ClientBase<LocalPIData.cems.cemsSoap>, LocalPIData.cems.cemsSoap {
        
        public cemsSoapClient() {
        }
        
        public cemsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public cemsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public cemsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public cemsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LocalPIData.cems.HelloWorldResponse LocalPIData.cems.cemsSoap.HelloWorld(LocalPIData.cems.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            LocalPIData.cems.HelloWorldRequest inValue = new LocalPIData.cems.HelloWorldRequest();
            inValue.Body = new LocalPIData.cems.HelloWorldRequestBody();
            LocalPIData.cems.HelloWorldResponse retVal = ((LocalPIData.cems.cemsSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LocalPIData.cems.AddPiRecordResponse LocalPIData.cems.cemsSoap.AddPiRecord(LocalPIData.cems.AddPiRecordRequest request) {
            return base.Channel.AddPiRecord(request);
        }
        
        public int AddPiRecord(System.DateTime ts, string pn, float pv, int mi, int pi) {
            LocalPIData.cems.AddPiRecordRequest inValue = new LocalPIData.cems.AddPiRecordRequest();
            inValue.Body = new LocalPIData.cems.AddPiRecordRequestBody();
            inValue.Body.ts = ts;
            inValue.Body.pn = pn;
            inValue.Body.pv = pv;
            inValue.Body.mi = mi;
            inValue.Body.pi = pi;
            LocalPIData.cems.AddPiRecordResponse retVal = ((LocalPIData.cems.cemsSoap)(this)).AddPiRecord(inValue);
            return retVal.Body.AddPiRecordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LocalPIData.cems.AddRuleLogRdResponse LocalPIData.cems.cemsSoap.AddRuleLogRd(LocalPIData.cems.AddRuleLogRdRequest request) {
            return base.Channel.AddRuleLogRd(request);
        }
        
        public int AddRuleLogRd(System.DateTime ts, string pn, string rn, string rt, string rd, int mi, int pi) {
            LocalPIData.cems.AddRuleLogRdRequest inValue = new LocalPIData.cems.AddRuleLogRdRequest();
            inValue.Body = new LocalPIData.cems.AddRuleLogRdRequestBody();
            inValue.Body.ts = ts;
            inValue.Body.pn = pn;
            inValue.Body.rn = rn;
            inValue.Body.rt = rt;
            inValue.Body.rd = rd;
            inValue.Body.mi = mi;
            inValue.Body.pi = pi;
            LocalPIData.cems.AddRuleLogRdResponse retVal = ((LocalPIData.cems.cemsSoap)(this)).AddRuleLogRd(inValue);
            return retVal.Body.AddRuleLogRdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LocalPIData.cems.UpdatePiRecordResponse LocalPIData.cems.cemsSoap.UpdatePiRecord(LocalPIData.cems.UpdatePiRecordRequest request) {
            return base.Channel.UpdatePiRecord(request);
        }
        
        public int UpdatePiRecord(System.DateTime ts, string pn, float pv, int mi, int pi) {
            LocalPIData.cems.UpdatePiRecordRequest inValue = new LocalPIData.cems.UpdatePiRecordRequest();
            inValue.Body = new LocalPIData.cems.UpdatePiRecordRequestBody();
            inValue.Body.ts = ts;
            inValue.Body.pn = pn;
            inValue.Body.pv = pv;
            inValue.Body.mi = mi;
            inValue.Body.pi = pi;
            LocalPIData.cems.UpdatePiRecordResponse retVal = ((LocalPIData.cems.cemsSoap)(this)).UpdatePiRecord(inValue);
            return retVal.Body.UpdatePiRecordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LocalPIData.cems.UpdateRuleLogRdResponse LocalPIData.cems.cemsSoap.UpdateRuleLogRd(LocalPIData.cems.UpdateRuleLogRdRequest request) {
            return base.Channel.UpdateRuleLogRd(request);
        }
        
        public int UpdateRuleLogRd(System.DateTime ts, string pn, string rn, string rt, string rd, int mi, int pi) {
            LocalPIData.cems.UpdateRuleLogRdRequest inValue = new LocalPIData.cems.UpdateRuleLogRdRequest();
            inValue.Body = new LocalPIData.cems.UpdateRuleLogRdRequestBody();
            inValue.Body.ts = ts;
            inValue.Body.pn = pn;
            inValue.Body.rn = rn;
            inValue.Body.rt = rt;
            inValue.Body.rd = rd;
            inValue.Body.mi = mi;
            inValue.Body.pi = pi;
            LocalPIData.cems.UpdateRuleLogRdResponse retVal = ((LocalPIData.cems.cemsSoap)(this)).UpdateRuleLogRd(inValue);
            return retVal.Body.UpdateRuleLogRdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LocalPIData.cems.AddPiRecord_cResponse LocalPIData.cems.cemsSoap.AddPiRecord_c(LocalPIData.cems.AddPiRecord_cRequest request) {
            return base.Channel.AddPiRecord_c(request);
        }
        
        public int AddPiRecord_c(long lid, System.DateTime ts, string pn, float pv, int mi, int pi) {
            LocalPIData.cems.AddPiRecord_cRequest inValue = new LocalPIData.cems.AddPiRecord_cRequest();
            inValue.Body = new LocalPIData.cems.AddPiRecord_cRequestBody();
            inValue.Body.lid = lid;
            inValue.Body.ts = ts;
            inValue.Body.pn = pn;
            inValue.Body.pv = pv;
            inValue.Body.mi = mi;
            inValue.Body.pi = pi;
            LocalPIData.cems.AddPiRecord_cResponse retVal = ((LocalPIData.cems.cemsSoap)(this)).AddPiRecord_c(inValue);
            return retVal.Body.AddPiRecord_cResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LocalPIData.cems.UpdatePiRecord_cResponse LocalPIData.cems.cemsSoap.UpdatePiRecord_c(LocalPIData.cems.UpdatePiRecord_cRequest request) {
            return base.Channel.UpdatePiRecord_c(request);
        }
        
        public int UpdatePiRecord_c(long lid, System.DateTime ts, string pn, float pv, int mi, int pi) {
            LocalPIData.cems.UpdatePiRecord_cRequest inValue = new LocalPIData.cems.UpdatePiRecord_cRequest();
            inValue.Body = new LocalPIData.cems.UpdatePiRecord_cRequestBody();
            inValue.Body.lid = lid;
            inValue.Body.ts = ts;
            inValue.Body.pn = pn;
            inValue.Body.pv = pv;
            inValue.Body.mi = mi;
            inValue.Body.pi = pi;
            LocalPIData.cems.UpdatePiRecord_cResponse retVal = ((LocalPIData.cems.cemsSoap)(this)).UpdatePiRecord_c(inValue);
            return retVal.Body.UpdatePiRecord_cResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LocalPIData.cems.AddRuleLogRd_cResponse LocalPIData.cems.cemsSoap.AddRuleLogRd_c(LocalPIData.cems.AddRuleLogRd_cRequest request) {
            return base.Channel.AddRuleLogRd_c(request);
        }
        
        public int AddRuleLogRd_c(long lid, System.DateTime ts, string pn, string rt, string rd, string cemstype, int pi) {
            LocalPIData.cems.AddRuleLogRd_cRequest inValue = new LocalPIData.cems.AddRuleLogRd_cRequest();
            inValue.Body = new LocalPIData.cems.AddRuleLogRd_cRequestBody();
            inValue.Body.lid = lid;
            inValue.Body.ts = ts;
            inValue.Body.pn = pn;
            inValue.Body.rt = rt;
            inValue.Body.rd = rd;
            inValue.Body.cemstype = cemstype;
            inValue.Body.pi = pi;
            LocalPIData.cems.AddRuleLogRd_cResponse retVal = ((LocalPIData.cems.cemsSoap)(this)).AddRuleLogRd_c(inValue);
            return retVal.Body.AddRuleLogRd_cResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LocalPIData.cems.UpdateRuleLog_cResponse LocalPIData.cems.cemsSoap.UpdateRuleLog_c(LocalPIData.cems.UpdateRuleLog_cRequest request) {
            return base.Channel.UpdateRuleLog_c(request);
        }
        
        public int UpdateRuleLog_c(long lid, System.DateTime ts, string pn, string rt, string rd, string cemstype, int pi) {
            LocalPIData.cems.UpdateRuleLog_cRequest inValue = new LocalPIData.cems.UpdateRuleLog_cRequest();
            inValue.Body = new LocalPIData.cems.UpdateRuleLog_cRequestBody();
            inValue.Body.lid = lid;
            inValue.Body.ts = ts;
            inValue.Body.pn = pn;
            inValue.Body.rt = rt;
            inValue.Body.rd = rd;
            inValue.Body.cemstype = cemstype;
            inValue.Body.pi = pi;
            LocalPIData.cems.UpdateRuleLog_cResponse retVal = ((LocalPIData.cems.cemsSoap)(this)).UpdateRuleLog_c(inValue);
            return retVal.Body.UpdateRuleLog_cResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LocalPIData.cems.AddMonitorData_cResponse LocalPIData.cems.cemsSoap.AddMonitorData_c(LocalPIData.cems.AddMonitorData_cRequest request) {
            return base.Channel.AddMonitorData_c(request);
        }
        
        public int AddMonitorData_c(long lid, System.DateTime ts, string enterprise, string pn, int indicatorid, double indicatorvalue, int pi) {
            LocalPIData.cems.AddMonitorData_cRequest inValue = new LocalPIData.cems.AddMonitorData_cRequest();
            inValue.Body = new LocalPIData.cems.AddMonitorData_cRequestBody();
            inValue.Body.lid = lid;
            inValue.Body.ts = ts;
            inValue.Body.enterprise = enterprise;
            inValue.Body.pn = pn;
            inValue.Body.indicatorid = indicatorid;
            inValue.Body.indicatorvalue = indicatorvalue;
            inValue.Body.pi = pi;
            LocalPIData.cems.AddMonitorData_cResponse retVal = ((LocalPIData.cems.cemsSoap)(this)).AddMonitorData_c(inValue);
            return retVal.Body.AddMonitorData_cResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LocalPIData.cems.UpdateMonitorData_cResponse LocalPIData.cems.cemsSoap.UpdateMonitorData_c(LocalPIData.cems.UpdateMonitorData_cRequest request) {
            return base.Channel.UpdateMonitorData_c(request);
        }
        
        public int UpdateMonitorData_c(long lid, System.DateTime ts, string enterprise, string pn, int indicatorid, double indicatorvalue, int pi) {
            LocalPIData.cems.UpdateMonitorData_cRequest inValue = new LocalPIData.cems.UpdateMonitorData_cRequest();
            inValue.Body = new LocalPIData.cems.UpdateMonitorData_cRequestBody();
            inValue.Body.lid = lid;
            inValue.Body.ts = ts;
            inValue.Body.enterprise = enterprise;
            inValue.Body.pn = pn;
            inValue.Body.indicatorid = indicatorid;
            inValue.Body.indicatorvalue = indicatorvalue;
            inValue.Body.pi = pi;
            LocalPIData.cems.UpdateMonitorData_cResponse retVal = ((LocalPIData.cems.cemsSoap)(this)).UpdateMonitorData_c(inValue);
            return retVal.Body.UpdateMonitorData_cResult;
        }
        
        public int AddExceptionGroup_c(long lid, long envirid, int typeid, int pi) {
            return base.Channel.AddExceptionGroup_c(lid, envirid, typeid, pi);
        }
        
        public int UpdateExceptionGroup_c(long lid, long envirid, int typeid, int pi) {
            return base.Channel.UpdateExceptionGroup_c(lid, envirid, typeid, pi);
        }
        
        public int AddExceptionRuleLog_c(long lid, long envirid, long ruleid, int typeid, int pi) {
            return base.Channel.AddExceptionRuleLog_c(lid, envirid, ruleid, typeid, pi);
        }
        
        public int UpdateExceptionRuleLog_c(long lid, long envirid, long ruleid, int typeid, int pi) {
            return base.Channel.UpdateExceptionRuleLog_c(lid, envirid, ruleid, typeid, pi);
        }
    }
}
