//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnvirPortal_Data.cems {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="cems.cemsSoap")]
    public interface cemsSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 HelloWorldResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        EnvirPortal_Data.cems.HelloWorldResponse HelloWorld(EnvirPortal_Data.cems.HelloWorldRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 pn 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddPiRecord", ReplyAction="*")]
        EnvirPortal_Data.cems.AddPiRecordResponse AddPiRecord(EnvirPortal_Data.cems.AddPiRecordRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 pn 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddRuleLogRd", ReplyAction="*")]
        EnvirPortal_Data.cems.AddRuleLogRdResponse AddRuleLogRd(EnvirPortal_Data.cems.AddRuleLogRdRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 pn 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdatePiRecord", ReplyAction="*")]
        EnvirPortal_Data.cems.UpdatePiRecordResponse UpdatePiRecord(EnvirPortal_Data.cems.UpdatePiRecordRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 pn 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateRuleLogRd", ReplyAction="*")]
        EnvirPortal_Data.cems.UpdateRuleLogRdResponse UpdateRuleLogRd(EnvirPortal_Data.cems.UpdateRuleLogRdRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 pn 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddPiRecord_c", ReplyAction="*")]
        EnvirPortal_Data.cems.AddPiRecord_cResponse AddPiRecord_c(EnvirPortal_Data.cems.AddPiRecord_cRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 pn 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdatePiRecord_c", ReplyAction="*")]
        EnvirPortal_Data.cems.UpdatePiRecord_cResponse UpdatePiRecord_c(EnvirPortal_Data.cems.UpdatePiRecord_cRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 pn 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddRuleLogRd_c", ReplyAction="*")]
        EnvirPortal_Data.cems.AddRuleLogRd_cResponse AddRuleLogRd_c(EnvirPortal_Data.cems.AddRuleLogRd_cRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 pn 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateRuleLog_c", ReplyAction="*")]
        EnvirPortal_Data.cems.UpdateRuleLog_cResponse UpdateRuleLog_c(EnvirPortal_Data.cems.UpdateRuleLog_cRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 enterprise 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddMonitorData_c", ReplyAction="*")]
        EnvirPortal_Data.cems.AddMonitorData_cResponse AddMonitorData_c(EnvirPortal_Data.cems.AddMonitorData_cRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 enterprise 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateMonitorData_c", ReplyAction="*")]
        EnvirPortal_Data.cems.UpdateMonitorData_cResponse UpdateMonitorData_c(EnvirPortal_Data.cems.UpdateMonitorData_cRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddExceptionGroup_c", ReplyAction="*")]
        int AddExceptionGroup_c(long lid, long envirid, int typeid, int pi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateExceptionGroup_c", ReplyAction="*")]
        int UpdateExceptionGroup_c(long lid, long envirid, int typeid, int pi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddExceptionRuleLog_c", ReplyAction="*")]
        int AddExceptionRuleLog_c(long lid, long envirid, long ruleid, int typeid, int pi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateExceptionRuleLog_c", ReplyAction="*")]
        int UpdateExceptionRuleLog_c(long lid, long envirid, long ruleid, int typeid, int pi);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 pn 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddPiAvgRecord_c", ReplyAction="*")]
        EnvirPortal_Data.cems.AddPiAvgRecord_cResponse AddPiAvgRecord_c(EnvirPortal_Data.cems.AddPiAvgRecord_cRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 pn 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddCalibRecord_c", ReplyAction="*")]
        EnvirPortal_Data.cems.AddCalibRecord_cResponse AddCalibRecord_c(EnvirPortal_Data.cems.AddCalibRecord_cRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 pn 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddCalibRuleValueRecord_c", ReplyAction="*")]
        EnvirPortal_Data.cems.AddCalibRuleValueRecord_cResponse AddCalibRuleValueRecord_c(EnvirPortal_Data.cems.AddCalibRuleValueRecord_cRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public EnvirPortal_Data.cems.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(EnvirPortal_Data.cems.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public EnvirPortal_Data.cems.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(EnvirPortal_Data.cems.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddPiRecordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddPiRecord", Namespace="http://tempuri.org/", Order=0)]
        public EnvirPortal_Data.cems.AddPiRecordRequestBody Body;
        
        public AddPiRecordRequest() {
        }
        
        public AddPiRecordRequest(EnvirPortal_Data.cems.AddPiRecordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddPiRecordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime ts;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pn;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public float pv;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int mi;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int pi;
        
        public AddPiRecordRequestBody() {
        }
        
        public AddPiRecordRequestBody(System.DateTime ts, string pn, float pv, int mi, int pi) {
            this.ts = ts;
            this.pn = pn;
            this.pv = pv;
            this.mi = mi;
            this.pi = pi;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddPiRecordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddPiRecordResponse", Namespace="http://tempuri.org/", Order=0)]
        public EnvirPortal_Data.cems.AddPiRecordResponseBody Body;
        
        public AddPiRecordResponse() {
        }
        
        public AddPiRecordResponse(EnvirPortal_Data.cems.AddPiRecordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddPiRecordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int AddPiRecordResult;
        
        public AddPiRecordResponseBody() {
        }
        
        public AddPiRecordResponseBody(int AddPiRecordResult) {
            this.AddPiRecordResult = AddPiRecordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddRuleLogRdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddRuleLogRd", Namespace="http://tempuri.org/", Order=0)]
        public EnvirPortal_Data.cems.AddRuleLogRdRequestBody Body;
        
        public AddRuleLogRdRequest() {
        }
        
        public AddRuleLogRdRequest(EnvirPortal_Data.cems.AddRuleLogRdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddRuleLogRdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime ts;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pn;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string rn;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string rt;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string rd;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int mi;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int pi;
        
        public AddRuleLogRdRequestBody() {
        }
        
        public AddRuleLogRdRequestBody(System.DateTime ts, string pn, string rn, string rt, string rd, int mi, int pi) {
            this.ts = ts;
            this.pn = pn;
            this.rn = rn;
            this.rt = rt;
            this.rd = rd;
            this.mi = mi;
            this.pi = pi;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddRuleLogRdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddRuleLogRdResponse", Namespace="http://tempuri.org/", Order=0)]
        public EnvirPortal_Data.cems.AddRuleLogRdResponseBody Body;
        
        public AddRuleLogRdResponse() {
        }
        
        public AddRuleLogRdResponse(EnvirPortal_Data.cems.AddRuleLogRdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddRuleLogRdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int AddRuleLogRdResult;
        
        public AddRuleLogRdResponseBody() {
        }
        
        public AddRuleLogRdResponseBody(int AddRuleLogRdResult) {
            this.AddRuleLogRdResult = AddRuleLogRdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdatePiRecordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdatePiRecord", Namespace="http://tempuri.org/", Order=0)]
        public EnvirPortal_Data.cems.UpdatePiRecordRequestBody Body;
        
        public UpdatePiRecordRequest() {
        }
        
        public UpdatePiRecordRequest(EnvirPortal_Data.cems.UpdatePiRecordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdatePiRecordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime ts;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pn;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public float pv;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int mi;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int pi;
        
        public UpdatePiRecordRequestBody() {
        }
        
        public UpdatePiRecordRequestBody(System.DateTime ts, string pn, float pv, int mi, int pi) {
            this.ts = ts;
            this.pn = pn;
            this.pv = pv;
            this.mi = mi;
            this.pi = pi;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdatePiRecordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdatePiRecordResponse", Namespace="http://tempuri.org/", Order=0)]
        public EnvirPortal_Data.cems.UpdatePiRecordResponseBody Body;
        
        public UpdatePiRecordResponse() {
        }
        
        public UpdatePiRecordResponse(EnvirPortal_Data.cems.UpdatePiRecordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdatePiRecordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int UpdatePiRecordResult;
        
        public UpdatePiRecordResponseBody() {
        }
        
        public UpdatePiRecordResponseBody(int UpdatePiRecordResult) {
            this.UpdatePiRecordResult = UpdatePiRecordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateRuleLogRdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateRuleLogRd", Namespace="http://tempuri.org/", Order=0)]
        public EnvirPortal_Data.cems.UpdateRuleLogRdRequestBody Body;
        
        public UpdateRuleLogRdRequest() {
        }
        
        public UpdateRuleLogRdRequest(EnvirPortal_Data.cems.UpdateRuleLogRdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateRuleLogRdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime ts;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pn;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string rn;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string rt;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string rd;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int mi;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int pi;
        
        public UpdateRuleLogRdRequestBody() {
        }
        
        public UpdateRuleLogRdRequestBody(System.DateTime ts, string pn, string rn, string rt, string rd, int mi, int pi) {
            this.ts = ts;
            this.pn = pn;
            this.rn = rn;
            this.rt = rt;
            this.rd = rd;
            this.mi = mi;
            this.pi = pi;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateRuleLogRdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateRuleLogRdResponse", Namespace="http://tempuri.org/", Order=0)]
        public EnvirPortal_Data.cems.UpdateRuleLogRdResponseBody Body;
        
        public UpdateRuleLogRdResponse() {
        }
        
        public UpdateRuleLogRdResponse(EnvirPortal_Data.cems.UpdateRuleLogRdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateRuleLogRdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int UpdateRuleLogRdResult;
        
        public UpdateRuleLogRdResponseBody() {
        }
        
        public UpdateRuleLogRdResponseBody(int UpdateRuleLogRdResult) {
            this.UpdateRuleLogRdResult = UpdateRuleLogRdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddPiRecord_cRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddPiRecord_c", Namespace="http://tempuri.org/", Order=0)]
        public EnvirPortal_Data.cems.AddPiRecord_cRequestBody Body;
        
        public AddPiRecord_cRequest() {
        }
        
        public AddPiRecord_cRequest(EnvirPortal_Data.cems.AddPiRecord_cRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddPiRecord_cRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long lid;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime ts;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string pn;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public float pv;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int mi;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int pi;
        
        public AddPiRecord_cRequestBody() {
        }
        
        public AddPiRecord_cRequestBody(long lid, System.DateTime ts, string pn, float pv, int mi, int pi) {
            this.lid = lid;
            this.ts = ts;
            this.pn = pn;
            this.pv = pv;
            this.mi = mi;
            this.pi = pi;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddPiRecord_cResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddPiRecord_cResponse", Namespace="http://tempuri.org/", Order=0)]
        public EnvirPortal_Data.cems.AddPiRecord_cResponseBody Body;
        
        public AddPiRecord_cResponse() {
        }
        
        public AddPiRecord_cResponse(EnvirPortal_Data.cems.AddPiRecord_cResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddPiRecord_cResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int AddPiRecord_cResult;
        
        public AddPiRecord_cResponseBody() {
        }
        
        public AddPiRecord_cResponseBody(int AddPiRecord_cResult) {
            this.AddPiRecord_cResult = AddPiRecord_cResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdatePiRecord_cRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdatePiRecord_c", Namespace="http://tempuri.org/", Order=0)]
        public EnvirPortal_Data.cems.UpdatePiRecord_cRequestBody Body;
        
        public UpdatePiRecord_cRequest() {
        }
        
        public UpdatePiRecord_cRequest(EnvirPortal_Data.cems.UpdatePiRecord_cRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdatePiRecord_cRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long lid;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime ts;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string pn;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public float pv;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int mi;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int pi;
        
        public UpdatePiRecord_cRequestBody() {
        }
        
        public UpdatePiRecord_cRequestBody(long lid, System.DateTime ts, string pn, float pv, int mi, int pi) {
            this.lid = lid;
            this.ts = ts;
            this.pn = pn;
            this.pv = pv;
            this.mi = mi;
            this.pi = pi;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdatePiRecord_cResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdatePiRecord_cResponse", Namespace="http://tempuri.org/", Order=0)]
        public EnvirPortal_Data.cems.UpdatePiRecord_cResponseBody Body;
        
        public UpdatePiRecord_cResponse() {
        }
        
        public UpdatePiRecord_cResponse(EnvirPortal_Data.cems.UpdatePiRecord_cResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdatePiRecord_cResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int UpdatePiRecord_cResult;
        
        public UpdatePiRecord_cResponseBody() {
        }
        
        public UpdatePiRecord_cResponseBody(int UpdatePiRecord_cResult) {
            this.UpdatePiRecord_cResult = UpdatePiRecord_cResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddRuleLogRd_cRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddRuleLogRd_c", Namespace="http://tempuri.org/", Order=0)]
        public EnvirPortal_Data.cems.AddRuleLogRd_cRequestBody Body;
        
        public AddRuleLogRd_cRequest() {
        }
        
        public AddRuleLogRd_cRequest(EnvirPortal_Data.cems.AddRuleLogRd_cRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddRuleLogRd_cRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long lid;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime ts;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string pn;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string rt;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string rd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string cemstype;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int pi;
        
        public AddRuleLogRd_cRequestBody() {
        }
        
        public AddRuleLogRd_cRequestBody(long lid, System.DateTime ts, string pn, string rt, string rd, string cemstype, int pi) {
            this.lid = lid;
            this.ts = ts;
            this.pn = pn;
            this.rt = rt;
            this.rd = rd;
            this.cemstype = cemstype;
            this.pi = pi;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddRuleLogRd_cResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddRuleLogRd_cResponse", Namespace="http://tempuri.org/", Order=0)]
        public EnvirPortal_Data.cems.AddRuleLogRd_cResponseBody Body;
        
        public AddRuleLogRd_cResponse() {
        }
        
        public AddRuleLogRd_cResponse(EnvirPortal_Data.cems.AddRuleLogRd_cResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddRuleLogRd_cResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int AddRuleLogRd_cResult;
        
        public AddRuleLogRd_cResponseBody() {
        }
        
        public AddRuleLogRd_cResponseBody(int AddRuleLogRd_cResult) {
            this.AddRuleLogRd_cResult = AddRuleLogRd_cResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateRuleLog_cRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateRuleLog_c", Namespace="http://tempuri.org/", Order=0)]
        public EnvirPortal_Data.cems.UpdateRuleLog_cRequestBody Body;
        
        public UpdateRuleLog_cRequest() {
        }
        
        public UpdateRuleLog_cRequest(EnvirPortal_Data.cems.UpdateRuleLog_cRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateRuleLog_cRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long lid;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime ts;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string pn;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string rt;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string rd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string cemstype;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int pi;
        
        public UpdateRuleLog_cRequestBody() {
        }
        
        public UpdateRuleLog_cRequestBody(long lid, System.DateTime ts, string pn, string rt, string rd, string cemstype, int pi) {
            this.lid = lid;
            this.ts = ts;
            this.pn = pn;
            this.rt = rt;
            this.rd = rd;
            this.cemstype = cemstype;
            this.pi = pi;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateRuleLog_cResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateRuleLog_cResponse", Namespace="http://tempuri.org/", Order=0)]
        public EnvirPortal_Data.cems.UpdateRuleLog_cResponseBody Body;
        
        public UpdateRuleLog_cResponse() {
        }
        
        public UpdateRuleLog_cResponse(EnvirPortal_Data.cems.UpdateRuleLog_cResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateRuleLog_cResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int UpdateRuleLog_cResult;
        
        public UpdateRuleLog_cResponseBody() {
        }
        
        public UpdateRuleLog_cResponseBody(int UpdateRuleLog_cResult) {
            this.UpdateRuleLog_cResult = UpdateRuleLog_cResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddMonitorData_cRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddMonitorData_c", Namespace="http://tempuri.org/", Order=0)]
        public EnvirPortal_Data.cems.AddMonitorData_cRequestBody Body;
        
        public AddMonitorData_cRequest() {
        }
        
        public AddMonitorData_cRequest(EnvirPortal_Data.cems.AddMonitorData_cRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddMonitorData_cRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long lid;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime ts;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string enterprise;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string pn;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int indicatorid;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public double indicatorvalue;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int pi;
        
        public AddMonitorData_cRequestBody() {
        }
        
        public AddMonitorData_cRequestBody(long lid, System.DateTime ts, string enterprise, string pn, int indicatorid, double indicatorvalue, int pi) {
            this.lid = lid;
            this.ts = ts;
            this.enterprise = enterprise;
            this.pn = pn;
            this.indicatorid = indicatorid;
            this.indicatorvalue = indicatorvalue;
            this.pi = pi;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddMonitorData_cResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddMonitorData_cResponse", Namespace="http://tempuri.org/", Order=0)]
        public EnvirPortal_Data.cems.AddMonitorData_cResponseBody Body;
        
        public AddMonitorData_cResponse() {
        }
        
        public AddMonitorData_cResponse(EnvirPortal_Data.cems.AddMonitorData_cResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddMonitorData_cResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int AddMonitorData_cResult;
        
        public AddMonitorData_cResponseBody() {
        }
        
        public AddMonitorData_cResponseBody(int AddMonitorData_cResult) {
            this.AddMonitorData_cResult = AddMonitorData_cResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateMonitorData_cRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateMonitorData_c", Namespace="http://tempuri.org/", Order=0)]
        public EnvirPortal_Data.cems.UpdateMonitorData_cRequestBody Body;
        
        public UpdateMonitorData_cRequest() {
        }
        
        public UpdateMonitorData_cRequest(EnvirPortal_Data.cems.UpdateMonitorData_cRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateMonitorData_cRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long lid;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime ts;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string enterprise;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string pn;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int indicatorid;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public double indicatorvalue;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int pi;
        
        public UpdateMonitorData_cRequestBody() {
        }
        
        public UpdateMonitorData_cRequestBody(long lid, System.DateTime ts, string enterprise, string pn, int indicatorid, double indicatorvalue, int pi) {
            this.lid = lid;
            this.ts = ts;
            this.enterprise = enterprise;
            this.pn = pn;
            this.indicatorid = indicatorid;
            this.indicatorvalue = indicatorvalue;
            this.pi = pi;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateMonitorData_cResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateMonitorData_cResponse", Namespace="http://tempuri.org/", Order=0)]
        public EnvirPortal_Data.cems.UpdateMonitorData_cResponseBody Body;
        
        public UpdateMonitorData_cResponse() {
        }
        
        public UpdateMonitorData_cResponse(EnvirPortal_Data.cems.UpdateMonitorData_cResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateMonitorData_cResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int UpdateMonitorData_cResult;
        
        public UpdateMonitorData_cResponseBody() {
        }
        
        public UpdateMonitorData_cResponseBody(int UpdateMonitorData_cResult) {
            this.UpdateMonitorData_cResult = UpdateMonitorData_cResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddPiAvgRecord_cRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddPiAvgRecord_c", Namespace="http://tempuri.org/", Order=0)]
        public EnvirPortal_Data.cems.AddPiAvgRecord_cRequestBody Body;
        
        public AddPiAvgRecord_cRequest() {
        }
        
        public AddPiAvgRecord_cRequest(EnvirPortal_Data.cems.AddPiAvgRecord_cRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddPiAvgRecord_cRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pn;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public float pv;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime ts;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime ut;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int pi;
        
        public AddPiAvgRecord_cRequestBody() {
        }
        
        public AddPiAvgRecord_cRequestBody(string pn, float pv, System.DateTime ts, System.DateTime ut, int pi) {
            this.pn = pn;
            this.pv = pv;
            this.ts = ts;
            this.ut = ut;
            this.pi = pi;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddPiAvgRecord_cResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddPiAvgRecord_cResponse", Namespace="http://tempuri.org/", Order=0)]
        public EnvirPortal_Data.cems.AddPiAvgRecord_cResponseBody Body;
        
        public AddPiAvgRecord_cResponse() {
        }
        
        public AddPiAvgRecord_cResponse(EnvirPortal_Data.cems.AddPiAvgRecord_cResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddPiAvgRecord_cResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int AddPiAvgRecord_cResult;
        
        public AddPiAvgRecord_cResponseBody() {
        }
        
        public AddPiAvgRecord_cResponseBody(int AddPiAvgRecord_cResult) {
            this.AddPiAvgRecord_cResult = AddPiAvgRecord_cResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddCalibRecord_cRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddCalibRecord_c", Namespace="http://tempuri.org/", Order=0)]
        public EnvirPortal_Data.cems.AddCalibRecord_cRequestBody Body;
        
        public AddCalibRecord_cRequest() {
        }
        
        public AddCalibRecord_cRequest(EnvirPortal_Data.cems.AddCalibRecord_cRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddCalibRecord_cRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pn;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime st;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime et;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int pi;
        
        public AddCalibRecord_cRequestBody() {
        }
        
        public AddCalibRecord_cRequestBody(string pn, System.DateTime st, System.DateTime et, int pi) {
            this.pn = pn;
            this.st = st;
            this.et = et;
            this.pi = pi;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddCalibRecord_cResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddCalibRecord_cResponse", Namespace="http://tempuri.org/", Order=0)]
        public EnvirPortal_Data.cems.AddCalibRecord_cResponseBody Body;
        
        public AddCalibRecord_cResponse() {
        }
        
        public AddCalibRecord_cResponse(EnvirPortal_Data.cems.AddCalibRecord_cResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddCalibRecord_cResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int AddCalibRecord_cResult;
        
        public AddCalibRecord_cResponseBody() {
        }
        
        public AddCalibRecord_cResponseBody(int AddCalibRecord_cResult) {
            this.AddCalibRecord_cResult = AddCalibRecord_cResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddCalibRuleValueRecord_cRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddCalibRuleValueRecord_c", Namespace="http://tempuri.org/", Order=0)]
        public EnvirPortal_Data.cems.AddCalibRuleValueRecord_cRequestBody Body;
        
        public AddCalibRuleValueRecord_cRequest() {
        }
        
        public AddCalibRuleValueRecord_cRequest(EnvirPortal_Data.cems.AddCalibRuleValueRecord_cRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddCalibRuleValueRecord_cRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pn;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public float pv;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime ts;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime ut;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int pi;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int am;
        
        public AddCalibRuleValueRecord_cRequestBody() {
        }
        
        public AddCalibRuleValueRecord_cRequestBody(string pn, float pv, System.DateTime ts, System.DateTime ut, int pi, int am) {
            this.pn = pn;
            this.pv = pv;
            this.ts = ts;
            this.ut = ut;
            this.pi = pi;
            this.am = am;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddCalibRuleValueRecord_cResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddCalibRuleValueRecord_cResponse", Namespace="http://tempuri.org/", Order=0)]
        public EnvirPortal_Data.cems.AddCalibRuleValueRecord_cResponseBody Body;
        
        public AddCalibRuleValueRecord_cResponse() {
        }
        
        public AddCalibRuleValueRecord_cResponse(EnvirPortal_Data.cems.AddCalibRuleValueRecord_cResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddCalibRuleValueRecord_cResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int AddCalibRuleValueRecord_cResult;
        
        public AddCalibRuleValueRecord_cResponseBody() {
        }
        
        public AddCalibRuleValueRecord_cResponseBody(int AddCalibRuleValueRecord_cResult) {
            this.AddCalibRuleValueRecord_cResult = AddCalibRuleValueRecord_cResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface cemsSoapChannel : EnvirPortal_Data.cems.cemsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class cemsSoapClient : System.ServiceModel.ClientBase<EnvirPortal_Data.cems.cemsSoap>, EnvirPortal_Data.cems.cemsSoap {
        
        public cemsSoapClient() {
        }
        
        public cemsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public cemsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public cemsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public cemsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EnvirPortal_Data.cems.HelloWorldResponse EnvirPortal_Data.cems.cemsSoap.HelloWorld(EnvirPortal_Data.cems.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            EnvirPortal_Data.cems.HelloWorldRequest inValue = new EnvirPortal_Data.cems.HelloWorldRequest();
            inValue.Body = new EnvirPortal_Data.cems.HelloWorldRequestBody();
            EnvirPortal_Data.cems.HelloWorldResponse retVal = ((EnvirPortal_Data.cems.cemsSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EnvirPortal_Data.cems.AddPiRecordResponse EnvirPortal_Data.cems.cemsSoap.AddPiRecord(EnvirPortal_Data.cems.AddPiRecordRequest request) {
            return base.Channel.AddPiRecord(request);
        }
        
        public int AddPiRecord(System.DateTime ts, string pn, float pv, int mi, int pi) {
            EnvirPortal_Data.cems.AddPiRecordRequest inValue = new EnvirPortal_Data.cems.AddPiRecordRequest();
            inValue.Body = new EnvirPortal_Data.cems.AddPiRecordRequestBody();
            inValue.Body.ts = ts;
            inValue.Body.pn = pn;
            inValue.Body.pv = pv;
            inValue.Body.mi = mi;
            inValue.Body.pi = pi;
            EnvirPortal_Data.cems.AddPiRecordResponse retVal = ((EnvirPortal_Data.cems.cemsSoap)(this)).AddPiRecord(inValue);
            return retVal.Body.AddPiRecordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EnvirPortal_Data.cems.AddRuleLogRdResponse EnvirPortal_Data.cems.cemsSoap.AddRuleLogRd(EnvirPortal_Data.cems.AddRuleLogRdRequest request) {
            return base.Channel.AddRuleLogRd(request);
        }
        
        public int AddRuleLogRd(System.DateTime ts, string pn, string rn, string rt, string rd, int mi, int pi) {
            EnvirPortal_Data.cems.AddRuleLogRdRequest inValue = new EnvirPortal_Data.cems.AddRuleLogRdRequest();
            inValue.Body = new EnvirPortal_Data.cems.AddRuleLogRdRequestBody();
            inValue.Body.ts = ts;
            inValue.Body.pn = pn;
            inValue.Body.rn = rn;
            inValue.Body.rt = rt;
            inValue.Body.rd = rd;
            inValue.Body.mi = mi;
            inValue.Body.pi = pi;
            EnvirPortal_Data.cems.AddRuleLogRdResponse retVal = ((EnvirPortal_Data.cems.cemsSoap)(this)).AddRuleLogRd(inValue);
            return retVal.Body.AddRuleLogRdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EnvirPortal_Data.cems.UpdatePiRecordResponse EnvirPortal_Data.cems.cemsSoap.UpdatePiRecord(EnvirPortal_Data.cems.UpdatePiRecordRequest request) {
            return base.Channel.UpdatePiRecord(request);
        }
        
        public int UpdatePiRecord(System.DateTime ts, string pn, float pv, int mi, int pi) {
            EnvirPortal_Data.cems.UpdatePiRecordRequest inValue = new EnvirPortal_Data.cems.UpdatePiRecordRequest();
            inValue.Body = new EnvirPortal_Data.cems.UpdatePiRecordRequestBody();
            inValue.Body.ts = ts;
            inValue.Body.pn = pn;
            inValue.Body.pv = pv;
            inValue.Body.mi = mi;
            inValue.Body.pi = pi;
            EnvirPortal_Data.cems.UpdatePiRecordResponse retVal = ((EnvirPortal_Data.cems.cemsSoap)(this)).UpdatePiRecord(inValue);
            return retVal.Body.UpdatePiRecordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EnvirPortal_Data.cems.UpdateRuleLogRdResponse EnvirPortal_Data.cems.cemsSoap.UpdateRuleLogRd(EnvirPortal_Data.cems.UpdateRuleLogRdRequest request) {
            return base.Channel.UpdateRuleLogRd(request);
        }
        
        public int UpdateRuleLogRd(System.DateTime ts, string pn, string rn, string rt, string rd, int mi, int pi) {
            EnvirPortal_Data.cems.UpdateRuleLogRdRequest inValue = new EnvirPortal_Data.cems.UpdateRuleLogRdRequest();
            inValue.Body = new EnvirPortal_Data.cems.UpdateRuleLogRdRequestBody();
            inValue.Body.ts = ts;
            inValue.Body.pn = pn;
            inValue.Body.rn = rn;
            inValue.Body.rt = rt;
            inValue.Body.rd = rd;
            inValue.Body.mi = mi;
            inValue.Body.pi = pi;
            EnvirPortal_Data.cems.UpdateRuleLogRdResponse retVal = ((EnvirPortal_Data.cems.cemsSoap)(this)).UpdateRuleLogRd(inValue);
            return retVal.Body.UpdateRuleLogRdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EnvirPortal_Data.cems.AddPiRecord_cResponse EnvirPortal_Data.cems.cemsSoap.AddPiRecord_c(EnvirPortal_Data.cems.AddPiRecord_cRequest request) {
            return base.Channel.AddPiRecord_c(request);
        }
        
        public int AddPiRecord_c(long lid, System.DateTime ts, string pn, float pv, int mi, int pi) {
            EnvirPortal_Data.cems.AddPiRecord_cRequest inValue = new EnvirPortal_Data.cems.AddPiRecord_cRequest();
            inValue.Body = new EnvirPortal_Data.cems.AddPiRecord_cRequestBody();
            inValue.Body.lid = lid;
            inValue.Body.ts = ts;
            inValue.Body.pn = pn;
            inValue.Body.pv = pv;
            inValue.Body.mi = mi;
            inValue.Body.pi = pi;
            EnvirPortal_Data.cems.AddPiRecord_cResponse retVal = ((EnvirPortal_Data.cems.cemsSoap)(this)).AddPiRecord_c(inValue);
            return retVal.Body.AddPiRecord_cResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EnvirPortal_Data.cems.UpdatePiRecord_cResponse EnvirPortal_Data.cems.cemsSoap.UpdatePiRecord_c(EnvirPortal_Data.cems.UpdatePiRecord_cRequest request) {
            return base.Channel.UpdatePiRecord_c(request);
        }
        
        public int UpdatePiRecord_c(long lid, System.DateTime ts, string pn, float pv, int mi, int pi) {
            EnvirPortal_Data.cems.UpdatePiRecord_cRequest inValue = new EnvirPortal_Data.cems.UpdatePiRecord_cRequest();
            inValue.Body = new EnvirPortal_Data.cems.UpdatePiRecord_cRequestBody();
            inValue.Body.lid = lid;
            inValue.Body.ts = ts;
            inValue.Body.pn = pn;
            inValue.Body.pv = pv;
            inValue.Body.mi = mi;
            inValue.Body.pi = pi;
            EnvirPortal_Data.cems.UpdatePiRecord_cResponse retVal = ((EnvirPortal_Data.cems.cemsSoap)(this)).UpdatePiRecord_c(inValue);
            return retVal.Body.UpdatePiRecord_cResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EnvirPortal_Data.cems.AddRuleLogRd_cResponse EnvirPortal_Data.cems.cemsSoap.AddRuleLogRd_c(EnvirPortal_Data.cems.AddRuleLogRd_cRequest request) {
            return base.Channel.AddRuleLogRd_c(request);
        }
        
        public int AddRuleLogRd_c(long lid, System.DateTime ts, string pn, string rt, string rd, string cemstype, int pi) {
            EnvirPortal_Data.cems.AddRuleLogRd_cRequest inValue = new EnvirPortal_Data.cems.AddRuleLogRd_cRequest();
            inValue.Body = new EnvirPortal_Data.cems.AddRuleLogRd_cRequestBody();
            inValue.Body.lid = lid;
            inValue.Body.ts = ts;
            inValue.Body.pn = pn;
            inValue.Body.rt = rt;
            inValue.Body.rd = rd;
            inValue.Body.cemstype = cemstype;
            inValue.Body.pi = pi;
            EnvirPortal_Data.cems.AddRuleLogRd_cResponse retVal = ((EnvirPortal_Data.cems.cemsSoap)(this)).AddRuleLogRd_c(inValue);
            return retVal.Body.AddRuleLogRd_cResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EnvirPortal_Data.cems.UpdateRuleLog_cResponse EnvirPortal_Data.cems.cemsSoap.UpdateRuleLog_c(EnvirPortal_Data.cems.UpdateRuleLog_cRequest request) {
            return base.Channel.UpdateRuleLog_c(request);
        }
        
        public int UpdateRuleLog_c(long lid, System.DateTime ts, string pn, string rt, string rd, string cemstype, int pi) {
            EnvirPortal_Data.cems.UpdateRuleLog_cRequest inValue = new EnvirPortal_Data.cems.UpdateRuleLog_cRequest();
            inValue.Body = new EnvirPortal_Data.cems.UpdateRuleLog_cRequestBody();
            inValue.Body.lid = lid;
            inValue.Body.ts = ts;
            inValue.Body.pn = pn;
            inValue.Body.rt = rt;
            inValue.Body.rd = rd;
            inValue.Body.cemstype = cemstype;
            inValue.Body.pi = pi;
            EnvirPortal_Data.cems.UpdateRuleLog_cResponse retVal = ((EnvirPortal_Data.cems.cemsSoap)(this)).UpdateRuleLog_c(inValue);
            return retVal.Body.UpdateRuleLog_cResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EnvirPortal_Data.cems.AddMonitorData_cResponse EnvirPortal_Data.cems.cemsSoap.AddMonitorData_c(EnvirPortal_Data.cems.AddMonitorData_cRequest request) {
            return base.Channel.AddMonitorData_c(request);
        }
        
        public int AddMonitorData_c(long lid, System.DateTime ts, string enterprise, string pn, int indicatorid, double indicatorvalue, int pi) {
            EnvirPortal_Data.cems.AddMonitorData_cRequest inValue = new EnvirPortal_Data.cems.AddMonitorData_cRequest();
            inValue.Body = new EnvirPortal_Data.cems.AddMonitorData_cRequestBody();
            inValue.Body.lid = lid;
            inValue.Body.ts = ts;
            inValue.Body.enterprise = enterprise;
            inValue.Body.pn = pn;
            inValue.Body.indicatorid = indicatorid;
            inValue.Body.indicatorvalue = indicatorvalue;
            inValue.Body.pi = pi;
            EnvirPortal_Data.cems.AddMonitorData_cResponse retVal = ((EnvirPortal_Data.cems.cemsSoap)(this)).AddMonitorData_c(inValue);
            return retVal.Body.AddMonitorData_cResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EnvirPortal_Data.cems.UpdateMonitorData_cResponse EnvirPortal_Data.cems.cemsSoap.UpdateMonitorData_c(EnvirPortal_Data.cems.UpdateMonitorData_cRequest request) {
            return base.Channel.UpdateMonitorData_c(request);
        }
        
        public int UpdateMonitorData_c(long lid, System.DateTime ts, string enterprise, string pn, int indicatorid, double indicatorvalue, int pi) {
            EnvirPortal_Data.cems.UpdateMonitorData_cRequest inValue = new EnvirPortal_Data.cems.UpdateMonitorData_cRequest();
            inValue.Body = new EnvirPortal_Data.cems.UpdateMonitorData_cRequestBody();
            inValue.Body.lid = lid;
            inValue.Body.ts = ts;
            inValue.Body.enterprise = enterprise;
            inValue.Body.pn = pn;
            inValue.Body.indicatorid = indicatorid;
            inValue.Body.indicatorvalue = indicatorvalue;
            inValue.Body.pi = pi;
            EnvirPortal_Data.cems.UpdateMonitorData_cResponse retVal = ((EnvirPortal_Data.cems.cemsSoap)(this)).UpdateMonitorData_c(inValue);
            return retVal.Body.UpdateMonitorData_cResult;
        }
        
        public int AddExceptionGroup_c(long lid, long envirid, int typeid, int pi) {
            return base.Channel.AddExceptionGroup_c(lid, envirid, typeid, pi);
        }
        
        public int UpdateExceptionGroup_c(long lid, long envirid, int typeid, int pi) {
            return base.Channel.UpdateExceptionGroup_c(lid, envirid, typeid, pi);
        }
        
        public int AddExceptionRuleLog_c(long lid, long envirid, long ruleid, int typeid, int pi) {
            return base.Channel.AddExceptionRuleLog_c(lid, envirid, ruleid, typeid, pi);
        }
        
        public int UpdateExceptionRuleLog_c(long lid, long envirid, long ruleid, int typeid, int pi) {
            return base.Channel.UpdateExceptionRuleLog_c(lid, envirid, ruleid, typeid, pi);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EnvirPortal_Data.cems.AddPiAvgRecord_cResponse EnvirPortal_Data.cems.cemsSoap.AddPiAvgRecord_c(EnvirPortal_Data.cems.AddPiAvgRecord_cRequest request) {
            return base.Channel.AddPiAvgRecord_c(request);
        }
        
        public int AddPiAvgRecord_c(string pn, float pv, System.DateTime ts, System.DateTime ut, int pi) {
            EnvirPortal_Data.cems.AddPiAvgRecord_cRequest inValue = new EnvirPortal_Data.cems.AddPiAvgRecord_cRequest();
            inValue.Body = new EnvirPortal_Data.cems.AddPiAvgRecord_cRequestBody();
            inValue.Body.pn = pn;
            inValue.Body.pv = pv;
            inValue.Body.ts = ts;
            inValue.Body.ut = ut;
            inValue.Body.pi = pi;
            EnvirPortal_Data.cems.AddPiAvgRecord_cResponse retVal = ((EnvirPortal_Data.cems.cemsSoap)(this)).AddPiAvgRecord_c(inValue);
            return retVal.Body.AddPiAvgRecord_cResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EnvirPortal_Data.cems.AddCalibRecord_cResponse EnvirPortal_Data.cems.cemsSoap.AddCalibRecord_c(EnvirPortal_Data.cems.AddCalibRecord_cRequest request) {
            return base.Channel.AddCalibRecord_c(request);
        }
        
        public int AddCalibRecord_c(string pn, System.DateTime st, System.DateTime et, int pi) {
            EnvirPortal_Data.cems.AddCalibRecord_cRequest inValue = new EnvirPortal_Data.cems.AddCalibRecord_cRequest();
            inValue.Body = new EnvirPortal_Data.cems.AddCalibRecord_cRequestBody();
            inValue.Body.pn = pn;
            inValue.Body.st = st;
            inValue.Body.et = et;
            inValue.Body.pi = pi;
            EnvirPortal_Data.cems.AddCalibRecord_cResponse retVal = ((EnvirPortal_Data.cems.cemsSoap)(this)).AddCalibRecord_c(inValue);
            return retVal.Body.AddCalibRecord_cResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EnvirPortal_Data.cems.AddCalibRuleValueRecord_cResponse EnvirPortal_Data.cems.cemsSoap.AddCalibRuleValueRecord_c(EnvirPortal_Data.cems.AddCalibRuleValueRecord_cRequest request) {
            return base.Channel.AddCalibRuleValueRecord_c(request);
        }
        
        public int AddCalibRuleValueRecord_c(string pn, float pv, System.DateTime ts, System.DateTime ut, int pi, int am) {
            EnvirPortal_Data.cems.AddCalibRuleValueRecord_cRequest inValue = new EnvirPortal_Data.cems.AddCalibRuleValueRecord_cRequest();
            inValue.Body = new EnvirPortal_Data.cems.AddCalibRuleValueRecord_cRequestBody();
            inValue.Body.pn = pn;
            inValue.Body.pv = pv;
            inValue.Body.ts = ts;
            inValue.Body.ut = ut;
            inValue.Body.pi = pi;
            inValue.Body.am = am;
            EnvirPortal_Data.cems.AddCalibRuleValueRecord_cResponse retVal = ((EnvirPortal_Data.cems.cemsSoap)(this)).AddCalibRuleValueRecord_c(inValue);
            return retVal.Body.AddCalibRuleValueRecord_cResult;
        }
    }
}
